### ISSUE TITLE
Release Package Only Includes Necessary Files

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-service-broker#142]
The current release zip archives include extraneous files and directories (e.g. `spec/` and `ci/` test directories). These should be excluded from the zip archive for published releases.

**Comment by izgeri** [comment]
@micahlee is the idea basically to specify exactly what goes into the ZIP as we do with the buildpack? That is, update what's included on this line:
https://github.com/cyberark/conjur-service-broker/blob/master/build.sh#L28

**Comment by izgeri** [comment]
you know I mostly added that comment to see the pretty github code snippet, and I am disappointed that it is not there :/

**Comment by micahlee** [comment]
Weird...

I notice that when I copy the reference (using the `Copy permalink` button):
![image](https://user-images.githubusercontent.com/1534633/73392491-f116db00-42a7-11ea-9440-b69163648732.png)

It does us a link straight to the commit ref, rather than the file generally. I wonder if that has something to do with it:
https://github.com/cyberark/conjur-service-broker/blob/78f04663032a774dda6488e9db3484ee73412ac2/build.sh#L28
