### ISSUE TITLE
Bump puma to 3.12.6 or higher

### ISSUE THREAD

**Issue by andytinkham** [cyberark/conjur-service-broker#198]
Puma has a CVE that affects versions prior to 3.12.6. I don't believe we're directly impacted but we should bump versions to close the CVE. 

However, simply bumping the version results in test failures that need to be investigated further.

**Comment by izgeri** [comment]
Note: see this issue comment for why we will **not** bump Puma to 3.12.6 for now: https://github.com/cyberark/conjur-service-broker/issues/178#issuecomment-657595764

**Comment by izgeri** [comment]
See also: https://github.com/cyberark/conjur-service-broker/pull/188

**Comment by andytinkham** [comment]
The linked issues in puma have been fixed, but bumping puma to 3.12.6 still causes test failures.
