### ISSUE TITLE
Service broker adds bind host to app layer automatically with v5 API

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur-service-broker#57]
Customers with thousands of apps are not going to be able to add each one to policy manually. For v4 we use host factories to allow new hosts to be added to a layer, which can have privileges granted to it, allowing hosts to automatically get these privileges.

The quickest way to solve the problem of automatically privileges hosts in v5 is probably to port over this v4 behavior. We will also need to update the v5 documentation to describe this workflow. The GitHub `README` should also be updated to not treat the host factory workflow as a v4-only thing.

AC:
- [ ] Hosts are automatically added to apps layer on bind for CONJUR_VERSION = 5
- [ ] Service broker tests for v5 apps layer functionality
- [ ] README documentation is updated with layer workflow for v4 and v5

**Comment by izgeri** [comment]
This is no longer worth doing, since we've come up with a stronger and more comprehensive plan for enabling easy entitlement of CF-deployed applications in #63.
