### ISSUE TITLE
Applications receive the URL of a Conjur follower on bind

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-service-broker#67]
Estimate days of effort: 1-2 days
Confidence level of ETA accuracy: 60%

## Overview
At current, applications receive the CONJUR_APPLIANCE_URL on bind that the service broker is configured with (eg the URL of the Conjur master). Applications authenticating with Conjur only perform read operations, however, and should therefore be configured to communicate with a Conjur follower.

To make this update, we'll add a new parameter to the service broker that gives it the follower URL.

AC:
- [x] service broker receives follower URL in an environment variable and sends that to CF apps on bind
- [x] Unit (RSpec) tests verify new functionality
- [x] Unit (RSpec) tests verify backward compatibility when follower is not configured
- [x] Integration (Cucumber) tests verify new functionality
- [x] Integration (Cucumber) tests verify backward compatibility when follower is not configured
- [x] README in repo is updated to explain new configuration parameter
- [x] issue created in [docs repo](https://github.com/cyberark/docs-cyberark-conjur-service-broker) to update tile docs to describe new configuration parameter
- [x] issue filed in [tile repo](https://github.com/conjurinc/cloudfoundry-conjur-tile) to update tile to add new configuration parameter

**Comment by micahlee** [comment]
Just thinking out loud: I wonder if there is any way to leverage the Envoy integration in PCF to provide applications with a load balanced route to all of the followers.

Alternatively, it would probably be a good idea to reiterate that in a Conjur cluster [there should be a load balancer](https://docs.conjur.org/Latest/en/Content/Deployment/HighAvailability/high_availability.html) in front of the followers, and that load-balanced address is what should be delivered to the applications.

**Comment by izgeri** [comment]
@micahlee I didn't specify here whether we should try to be backwards compatible, so if no follower URL is set it will still work - but I am leaning that we should be opinionated that you should specify a follower URL once this capability is on.

that may mean we also need to check the existence of this parameter in the health check, fwiw - otherwise someone could upgrade manually to the new version without adding this env var. if they deploy using the tile, however, they won't be able to do this - we can make the URL required in the tile.

**Comment by micahlee** [comment]
@izgeri So applications will *ONLY* get the follower address with this change, correct? Not both?
