### ISSUE TITLE
Service Broker Policy uses Human-Readable Names

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-service-broker#71]
By default the service broker only receives the GUID-based identifiers for org, space, and name. It may be desirable to use the human-readable names instead for policy to allow users to more easily read and understand policy and entitlements.

This will require the service broker to be able to access the CF Cloud Controller API with at least Auditor level access.

**Comment by mkkeffeler** [comment]
Wanted to note here, this is easier as of service broker api version 2.15, ```organization_name``` and ```space_name``` are part of the ```context``` object now. But with that said, this would be a huge change and needs to be rolled out with a "feature flag" so to speak. And since names can be edited, would require some work to handle those cases.

**Comment by izgeri** [comment]
I think with the changes in #238 we can close this older feature request as "wontfix" now :)
