### ISSUE TITLE
The scalable PCF integration has passed XA

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-service-broker#72]
Prereqs:
- Install CloudFoundry CLI: https://github.com/cloudfoundry/cli#installing-using-a-package-manager
- Create account on https://www.conjur.org/get-started/try-conjur.html
- Install CF Dev plugin for CF CLI: https://github.com/cloudfoundry-incubator/cfdev#install

Scenarios that should be validated:

- [x] 1. (Srdjan) I am trying out the Conjur PCF integration using the local demo repo
    > https://github.com/conjurdemos/cloudfoundry-conjur-demo/local

- [x] 3. (Srdjan & Micah) I am using the tile to install the service broker and buildpack into PCF via the Ops Manager following the PivNet documentation, and need to be able to privilege apps based on spaces
    > See 365 doc for Tile download and dev CloudFoundry info

    > PivNet docs for this release are available by running these commands:
    > ```
    > $ git clone -b 1.0-docs git@github.com:cyberark/docs-cyberark-conjur-service-broker.git
    > $ cd docs-cyberark-conjur-service-broker
    > $ ./run-bookbinder.sh
    > ```
    > And then open a browser to **http://localhost:4567**

    > Use `eval.conjur.org` Conjur info

- [x] 4. (Srdjan & Micah) I am trying out the Conjur PCF integration using the remote demo repo
    > https://github.com/conjurdemos/cloudfoundry-conjur-demo/pcf-with-installed-tile

- [x] 2.  (Srdjan) I am manually installing the service broker and buildpack into my own CF/PCF environment following the README instructions, and need to be able to privilege apps based on spaces
    > https://github.com/cyberark/conjur-service-broker/blob/master/README.md

    > Use `eval.conjur.org` Conjur info
   

- [x] 5. (Micah) I am using the buildpack and deploying a Java app
    > See 365 doc for sample Java app

- [x] 9. With preserve policy on, what happens to policy when you  provision multiple service instances per space, deprovision some, reprovision, etc

- [x] 7. (Srdjan & Micah) After deploying apps to PCF that use the service broker, I reload the root policy with `--replace` to remove a user
  - Note: the result of testing this scenario may just be a better understanding of the limitations of this integration at current. Revisions suggested by this scenario may be out of scope of this epic, but can be tracked in a future effort.
- [x] 8. (Both) Upgrade from configured 0.3.3 tile to configured 1.0.0 tile works
    > Potentially related to original issue seen: https://github.com/conjurinc/cloudfoundry-conjur-tile/pull/16/files#diff-c3f4bca5e1843b128d4555ec98e8764dR8
- [x] 6. (Both) I have a legacy (Conjur v4 EE) Conjur installation and I want to use the tile to deploy an app

**Comment by izgeri** [comment]
Noting *open questions* from the parent epic:
- Is org/space in the bind context only available in PCF? If this is also available in CF, what versions of CF support org/space information supplied on bind?
- Are the org/space GUIDs supplied on bind those of the service instance or of the application? If it is the org/space of the service instance, we may want to specifically advise users to provision a service instance per org/space for our SB.
- Should the tutorial also be updated as part of this update?

**Comment by sgnn7** [comment]
From XA of #3:
```
Issues
Service broker index
- Conjur API key - better description
- Url conjur follower - better description
- X509 description (nix paste)
- V4 host factory note needs to be in the table as well

- Your-pfc-policy-file.yml
    - Change comments from `/*` prefix to `#`
    - Make comments about v4 full-line comments, not suffixed to the line
    - Group ownership is wrong - needs to be absolute. This might be problematic if pcf policy isn't rooted in the root.
- Step 2
    - bottom needs to note to save the host API key produced by loading the policy into conjur
- Step 3
    - Might need to be removed from overview and added to installation instructions

Installing and Configuring
- Service broker config
    - Recommendation: should be a new section before installing page
    - Appliance URL: Should say eval.conjur.org if it's a test instance
    - Follower URL: Should mention that this is optional
    - Conjur Login: should say that this id is from policy
    - PCF Conjure Policy Branch ID: Use an example branch ID from loaded policy example
    - Conjur Certificate: needs better info on how to get cert. Maybe use openssl s_client. Definitely sub conjur appliance configured with conjur cli configured
    - Add click to save config

- There is no stem cell tab - probably needs removing
- Missing info after all the config you go to installation dashboard -> pending changes then click apply changes

Using service broker
- Step 1, Part 6 (new part) - Add info on how to set the variable value
- Step 4: add info on creating a space to deploy the app to
- Step 2: change "my-service-instance-name" to "conjur" (also match in step 3)
- Step 2: formatting issue with CLI commands of cf and policy
- Step 2: No showing on how to load the entitlement policy

Bug:
- Multiple service-instance can tie into same space so on cleanup, we don't check that and may erroneously delete org and space policies in conjur
```

**Comment by izgeri** [comment]
@micahlee please note here the bug issue # once you log it -  let's add that to a list of "known issues" for the 1.0.0 SB release and make the change for a 1.0.1 SB release.

since we haven't released the tile yet, I'd suggest we include the 1.0.1 SB in the 1.0.0 tile.

**Comment by micahlee** [comment]
To verify deleting a user without changing PCF policy

Load policy to define users:
```
- !user micah.lee
- !user srdjan.grubor
```
```
conjur policy load root users.yml
```

```
# conjur list
[
  "srdjan.grubor@cyberark.com:policy:root",
  "srdjan.grubor@cyberark.com:host:pcf-service-broker",
  "srdjan.grubor@cyberark.com:group:pcf-admin-group",
  "srdjan.grubor@cyberark.com:policy:pcf",
  "srdjan.grubor@cyberark.com:policy:pcf/production",
  "srdjan.grubor@cyberark.com:policy:space",
  "srdjan.grubor@cyberark.com:variable:space/database/username",
  "srdjan.grubor@cyberark.com:variable:space/database/password",
  "srdjan.grubor@cyberark.com:variable:space/stripe/private_key",
  "srdjan.grubor@cyberark.com:group:space/secrets-users",
  "srdjan.grubor@cyberark.com:group:space/secrets-managers",
  "srdjan.grubor@cyberark.com:cf-service-instance:pcf/production/c0200194-d705-4a1b-8d82-3669e813a426",
  "srdjan.grubor@cyberark.com:policy:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0",
  "srdjan.grubor@cyberark.com:layer:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0",
  "srdjan.grubor@cyberark.com:policy:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0/822f79e6-6c88-4e91-8c27-ce261ece1c5b",
  "srdjan.grubor@cyberark.com:layer:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0/822f79e6-6c88-4e91-8c27-ce261ece1c5b",
  "srdjan.grubor@cyberark.com:host:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0/822f79e6-6c88-4e91-8c27-ce261ece1c5b/9fb3bce0-01cb-4c0e-a11e-ab75492851d7",
  "srdjan.grubor@cyberark.com:cf-service-instance:pcf/production/8203d363-c619-4191-b8e6-382d805243e8",
  "srdjan.grubor@cyberark.com:policy:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1",
  "srdjan.grubor@cyberark.com:layer:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1",
  "srdjan.grubor@cyberark.com:policy:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1/8bf39f4a-ebde-437b-9c38-3d234b80631a",
  "srdjan.grubor@cyberark.com:layer:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1/8bf39f4a-ebde-437b-9c38-3d234b80631a",
  "srdjan.grubor@cyberark.com:user:micah.lee",
  "srdjan.grubor@cyberark.com:user:srdjan.grubor"
]
```

Load policy to delete `micah.lee`:
```
- !delete
  record: !user micah.lee
```
```
conjur policy load --delete root delete-user.yml
```

Result
```
# conjur list
[
  "srdjan.grubor@cyberark.com:policy:root",
  "srdjan.grubor@cyberark.com:host:pcf-service-broker",
  "srdjan.grubor@cyberark.com:group:pcf-admin-group",
  "srdjan.grubor@cyberark.com:policy:pcf",
  "srdjan.grubor@cyberark.com:policy:pcf/production",
  "srdjan.grubor@cyberark.com:policy:space",
  "srdjan.grubor@cyberark.com:variable:space/database/username",
  "srdjan.grubor@cyberark.com:variable:space/database/password",
  "srdjan.grubor@cyberark.com:variable:space/stripe/private_key",
  "srdjan.grubor@cyberark.com:group:space/secrets-users",
  "srdjan.grubor@cyberark.com:group:space/secrets-managers",
  "srdjan.grubor@cyberark.com:cf-service-instance:pcf/production/c0200194-d705-4a1b-8d82-3669e813a426",
  "srdjan.grubor@cyberark.com:policy:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0",
  "srdjan.grubor@cyberark.com:layer:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0",
  "srdjan.grubor@cyberark.com:policy:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0/822f79e6-6c88-4e91-8c27-ce261ece1c5b",
  "srdjan.grubor@cyberark.com:layer:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0/822f79e6-6c88-4e91-8c27-ce261ece1c5b",
  "srdjan.grubor@cyberark.com:host:pcf/production/a5c28954-eebe-45b1-a7c6-363b2ef68bd0/822f79e6-6c88-4e91-8c27-ce261ece1c5b/9fb3bce0-01cb-4c0e-a11e-ab75492851d7",
  "srdjan.grubor@cyberark.com:cf-service-instance:pcf/production/8203d363-c619-4191-b8e6-382d805243e8",
  "srdjan.grubor@cyberark.com:policy:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1",
  "srdjan.grubor@cyberark.com:layer:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1",
  "srdjan.grubor@cyberark.com:policy:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1/8bf39f4a-ebde-437b-9c38-3d234b80631a",
  "srdjan.grubor@cyberark.com:layer:pcf/production/cbd7a05a-b304-42a9-8f66-6827ae6f78a1/8bf39f4a-ebde-437b-9c38-3d234b80631a",
  "srdjan.grubor@cyberark.com:user:srdjan.grubor"
]
```

**Comment by sgnn7** [comment]
`4. I am trying out the Conjur PCF integration using the remote demo repo`

PCF dev tile with cloudfountdry-conjur-demo:
- needs better readme about pic demo launch
- Pcf-with-installed-tile
    - Readme in repo should link to docs on the installation part
    - Take out `cf marketplace` (no space to run it in)
    - Add info that you need to `export CONJUR_VERSION=5` for v5
    - V5 info doesn't include summon setup for cli to connect to conjur instance (cli init)
    - If something goes wrong, we should add a note that you should try deleting the org/space
    - Scripts should not have the daemon flag on docker commands (-d)
    - Note needs to be added that the policy for the scripts has to be rooted in "cf" path

**Comment by micahlee** [comment]
> 5. I am using the buildpack and deploying a Java app

Notes:
1. I didn't see any docs about where to put the `secrets.yml` file in the Java application. I knew from Slack discussion that the root directory wasn't correct, and I only knew where to put it from the sample app in Secretless.

2. I used a Java app in the context of the `cloudfoundry-conjur-demo` here: https://github.com/conjurdemos/cloudfoundry-conjur-demo/compare/java-demo-app.
    In this environment I:
    A) Setup the initial local demo environment with:
    ```
    $ cd local
    $ ./bin/start
    ```

    B) Built and deployed the Java app and received a supply buildpack error:
    ```
    $ cd ../app-java
    $ ./bin/build
    $ ./bin/deploy
    ...
    [cyberark-conjur-buildpack]: supplying
    No secrets.yml file found in /tmp/app.
    Failed to run all supply scripts: exit status 1
    ...
    ```

**Comment by izgeri** [comment]
Note - I've added a PR comment to add a note about where to place the secrets.yml to the docs PR [here](https://github.com/cyberark/docs-cyberark-conjur-service-broker/pull/7#discussion_r261320244)

**Comment by micahlee** [comment]
> **DRAFT**: These tasks are still in progress

# 8. Upgrade from configured 0.3.3 tile to configured 1.0.0 tile works

## Notes:
- I didn't locate any upgrade instructions in our docs. A good patter for this is the mysql upgrade docs: https://docs.pivotal.io/p-mysql/2-5/upgrade.html#upgrade-mysql-for-pcf

- A future upgrade doc (and perhaps the release notes) **MUST** inform the user that with the new supply buildpack, the buildpack will need to be specified in either the `manifest.yml` or the `cf push` command. (And apps need to be restaged?)



# 6. I have a legacy (Conjur v4 EE) Conjur installation and I want to use the tile to deploy an app

## Notes:
 - PivNet docs are missing policy load example for V4 entitlement.
 - PivNet docs don't mention that you may need to install the policy plugin for the v4 CLI:
    ```sh-session
    $ conjur policy load /data/policy_v4/grant_host.yml
    error: Unknown command 'policy'
    ```
    ```sh-session
    $ conjur plugin install policy
    Successfully installed conjur-asset-policy-0.13.0
    1 gem installed
    ```

**Comment by sgnn7** [comment]
`* I am manually installing the service broker and buildpack into my own CF/PCF environment following the README instructions, and need to be able to privilege apps based on spaces`

Works

Notes (cyberark/conjur-service-broker/blob/master/README.md Manual Install):
- Not clear that `SECURITY_USER_NAME` and `SECURITY_USER_PASSWORD` are arbitrary
- Needs a link maybe on how to configure the conjur instance
- Conjur policy need a link out to docs - current README leaves the user clueless on how to configure it and set groups/users/entitlements.
- `CONJUR_SSL_CERTIFICATE` isn't explained well - needs more details on how to get this maybe with openssl
- `CONJUR_PRESERVE_POLICY` not shown in `cf set-env list` that you need to set
- Need to use `$()` instead of backpacks in `APP_URL` snippet
- Make sure to note that `cf create-service` line indicates that `username_value` and `password_value` are just the same ones from `cf set-env conjur-service-broker SECURITY_USER_*` commands. Need to indicate that these are also not literal values.
- `When the Service Broker application is started` needs to be moved up to be right under `cf start concur-service-broker`
- Change `Installing the Conjur Buildpack` to make it clear that you _have_ to install the build pack for them to proceed if you use `summon` with the apps.
- Maybe show how to create space and make it a target right under `cf create-service cyberark-conjur community conjur`
-  Need to note how `conjur` parameter affects usage of apps in `cf create-service cyberark-conjur community conjur` command
- If `cf create-service cyberark-conjur community conjur` returns a 500 error, we should tell users to double-check their policies
- Show how to deploy the test app to see that thing works

**Comment by micahlee** [comment]
# 9. With preserve policy on, what happens to policy when you provision multiple service instances per space, deprovision some, reprovision, etc

This looks okay. I tested this using these steps:

1. Installed the Conjur Tile 1.0.0 and configured it with Preserve Policy on Deprovision set to true.
2. Ran `conjur list` to observe that there were no resources under my `cf` branch
3. Created a service instance in my space called `conjur`
4. Ran `conjur list` to observe that there were policies and layers for my org and space
5. Create another service instance in my space called `conjur2`
6. Loaded the secrets for the demo application into Conjur
7. Entitled the org and space layers to access their relevant secrets
8. Pushed the demo application to the space, binding it to the `conjur` service instance
9. Entitled the application to access its relevant secrets
10. Started the application and observed that it displayed its secret values for the app, space, and org in the weba pp.
11. Created a new Conjur service instance called `conjur3`
12. Restaged the app and observed that it still functioned correctly and could read the secret values.
13. Attempted to delete the service instance `conjur` and received the error that it could not be deleted because there were applications bound to it.
14. Deleted the service instance `conjur2`
15. Ran `conjur list` to observe that the policy branches and layers for the org and space were still present.
    > This is when the org and space would have been removed previously
16. Restaged the app and observed that it still functioned correctly and could read the secret values.
14. Deleted the service instance `conjur3`
15. Ran `conjur list` to observe that the policy branches and layers for the org and space were still present
17. Restaged the app and observed that it still functioned correctly and could read the secret values.

**Comment by sgnn7** [comment]
# 2 After deploying apps to PCF that use the service broker, I reload the root policy with --replace to remove a user

Looks like it works.

Loaded policies can be found here: 
- https://gist.github.com/sgnn7/b09a9fbb5bc250a14ae4966631ae84bc
- 2 credentials were added too but they're of no consequence to this test and PCF tile was configured with one service broker to generate a policy from it.

```
root@d5592d081a1e:/policy# conjur list
[
  "srdjan.grubor@cyberark.com:policy:root",
  "srdjan.grubor@cyberark.com:host:pcf-service-broker",
  "srdjan.grubor@cyberark.com:group:pcf-admin-group",
  "srdjan.grubor@cyberark.com:policy:pcf",
  "srdjan.grubor@cyberark.com:policy:pcf/production",
  "srdjan.grubor@cyberark.com:cf-service-instance:pcf/production/f024e466-9c40-4cd1-8f8b-f565e43b726c",
  "srdjan.grubor@cyberark.com:policy:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572",
  "srdjan.grubor@cyberark.com:layer:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572",
  "srdjan.grubor@cyberark.com:policy:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572/14796c67-3d15-4116-bbd3-e1c91b8ed30c",
  "srdjan.grubor@cyberark.com:layer:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572/14796c67-3d15-4116-bbd3-e1c91b8ed30c",
  "srdjan.grubor@cyberark.com:policy:pcf/space",
  "srdjan.grubor@cyberark.com:variable:pcf/space/database/username",
  "srdjan.grubor@cyberark.com:variable:pcf/space/database/password",
  "srdjan.grubor@cyberark.com:variable:pcf/space/stripe/private_key",
  "srdjan.grubor@cyberark.com:group:pcf/space/secrets-users",
  "srdjan.grubor@cyberark.com:group:pcf/space/secrets-managers",
  "srdjan.grubor@cyberark.com:host:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572/14796c67-3d15-4116-bbd3-e1c91b8ed30c/859cd48b-5cb7-40be-bc49-ab5c0621fcdf"
]

root@d5592d081a1e:/policy# conjur policy load --replace root /policy/your-pcf-policy-file.yml                                                                                                                                                                          

Loaded policy 'root'
{
  "created_roles": {
  },
  "version": 19
}

root@d5592d081a1e:/policy# conjur list
[
  "srdjan.grubor@cyberark.com:policy:root",
  "srdjan.grubor@cyberark.com:host:pcf-service-broker",
  "srdjan.grubor@cyberark.com:group:pcf-admin-group",
  "srdjan.grubor@cyberark.com:policy:pcf",
  "srdjan.grubor@cyberark.com:policy:pcf/production",
  "srdjan.grubor@cyberark.com:cf-service-instance:pcf/production/f024e466-9c40-4cd1-8f8b-f565e43b726c",
  "srdjan.grubor@cyberark.com:policy:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572",
  "srdjan.grubor@cyberark.com:layer:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572",
  "srdjan.grubor@cyberark.com:policy:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572/14796c67-3d15-4116-bbd3-e1c91b8ed30c",
  "srdjan.grubor@cyberark.com:layer:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572/14796c67-3d15-4116-bbd3-e1c91b8ed30c",
  "srdjan.grubor@cyberark.com:policy:pcf/space",
  "srdjan.grubor@cyberark.com:variable:pcf/space/database/username",
  "srdjan.grubor@cyberark.com:variable:pcf/space/database/password",
  "srdjan.grubor@cyberark.com:variable:pcf/space/stripe/private_key",
  "srdjan.grubor@cyberark.com:group:pcf/space/secrets-users",
  "srdjan.grubor@cyberark.com:group:pcf/space/secrets-managers",
  "srdjan.grubor@cyberark.com:host:pcf/production/d7ddf81d-dd04-437a-9ddc-3efa78f20572/14796c67-3d15-4116-bbd3-e1c91b8ed30c/859cd48b-5cb7-40be-bc49-ab5c0621fcdf"                                                                                                      
]
```

The diff between `conjur list` pre and post `conjur policy load --replace root /policy/your-pcf-policy-file.yml` is the same.

**Comment by jtuttle** [comment]
#  8. (Both) Upgrade from configured 0.3.3 tile to configured 1.0.0 tile works
This works if you rename the service-broker and service broker app before doing the upgrade:
```
cf target -o cyberark-conjur-org
cf rename-service-broker conjur_service_broker conjur-service-broker
cf rename conjur_service_broker-0.3.3 conjur-service-broker-0.3.3
```

**Comment by izgeri** [comment]
Final XA:
- [ ] Can install the 0.3.3 tile configured to work with v5 Conjur and upgrade from 0.3.3 to 1.0.0 following documentation (including buildpacks and updating to use the follower URL), and it works as 1.0.0 with an application
- [ ] Local v5 demo works as expected

**Comment by micahlee** [comment]
## Can install the 0.3.3 tile configured to work with v5 Conjur and upgrade from 0.3.3 to 1.0.0 following documentation (including buildpacks and updating to use the follower URL), and it works as 1.0.0 with an application

Steps taken:
```
	Completely clean up PCF instance on AWS
		Remove Tile
		Delete org
		Delete buildpacks
		Clean bosh packages
		List out `cf service-brokers`
		List out `cf orgs`
		List out `cf buildpacks`
	
	Install 0.3.3 Tile
		Configure to work with eval.conjur.org
		
	Configure and push app to fetch secrets from a Conjur service instance
	
	Capture State
		`cf service-brokers`
		`cf apps` within service broker space
		`cf orgs`
		`cf buildpacks`
		
	Upgrade 0.3.3 to 1.0.0 using docs 
		Configure follower address

	Ensure application
		Re-stage application
	
	Capture State
		`cf service-brokers`
		`cf apps` within service broker space
		`cf orgs`
		`cf buildpacks`
		
	Deploy second app
		See how it binds
		
	Create no-op service instance
	Rebind app to get new host ID
Re-entitle app to app secrets
```

Corresponding output from these steps are in a Gist here: https://gist.github.com/micahlee/0cb09dc8303205e5d072d94daf721366

**Comment by izgeri** [comment]
@micahlee @jtuttle based on discussions in slack, I moved this to _implemented_ - but can you please confirm that this item was completed?
> 6. (Both) I have a legacy (Conjur v4 EE) Conjur installation and I want to use the tile to deploy an app

**Comment by micahlee** [comment]
@izgeri, not satisfactorily, no. I mistakenly assumed the `Final XA` was a replacement of, rather than an extension to the prior tasks. I will do the V4 XA now.

**Comment by micahlee** [comment]
@izgeri, **now** the XA is complete.

The new tile works fine with Conjur V4, and I didn't encounter any issues with the docs for entitling applications.
