### ISSUE TITLE
Multiple service instances cause policy to be deleted on deprovision when service instance may still exist

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur-service-broker#95]
**Description**
Currently, the service broker will clean up the policy for the org and space when the service instance is deprovisioned, and the broker is not configured to preserve the policy. This currently does not account for the possibility of multiple Conjur service instances created in a given space.

**How to Reproduce the Behavior**
When a first service instance is created, the service broker will load the policy to define the policy and layer resources for the org and the space. When a second service instance is created, it will also load the same policy definitions, so there are now 2 service instances relying on the same Conjur resources for the org and space.

When either of these instance are deleted from the space, the service broker will remove the space resources (and the org, if there are no other spaces) without consideration for the other potential service instances relying on those Conjur resources.

**Expected Behavior**
Given a CloudFoundry instance when the Conjur Service Broker installed
And the "Preserve Policy" configuration is set to `false`

When I create a conjur service instance called `conjur-1`
Then the policy and layers exist for the org and space

When I create a conjur service instance called `conjur-2`
Then the policy and layers exist for the org and space

When I delete the conjur service instance called `conjur-1`
Then the policy and layers exist for the org and space

When I delete the conjur service instance called `conjur-2`
Then the policy and layers *DO NOT* exist for the org and space

**Workarounds**
- Enable `CONJUR_PRESERVE_POLICY` so that the policy is never removed on deprovision
- Only create a single Conjur Service Instance per space

**Comment by izgeri** [comment]
@micahlee reading this again, I'm not sure we need to fix this yet - we could fix for now by adding instructions to our docs. I'll share this with PM for feedback.

**Comment by izgeri** [comment]
also, we may address this by not allowing a second service instance to be provisioned (eg if on provision the space layer already exists, the provision should fail)

**Comment by micahlee** [comment]
> we may address this by not allowing a second service instance to be provisioned

Ah! I like that solution a lot. It was bothering me that we needed to come up with a solution for a situation that shouldn't really exist, and that would practically enforce the singleton nature of the service-instance per space.

**Comment by izgeri** [comment]
it's nice to have some real things happening on provision now :)

**Comment by izgeri** [comment]
Note: we need to take into account the "preserve policy" configuration
- if preserve policy is off, then deprovision removes the space, and we can check for the existence of the space on provision to ensure there is only one service instance (and fail provision if the space exists already)
- if preserve policy is on, then deprovision preserves the space - so we have no way of using the space layer to determine if the space already has a service instance. if someone deploys this way and later changes their config to "preserve policy" = off, this could be a mess.

is there a way to use the service instance ID in this logic @micahlee ?
