### ISSUE TITLE
Service broker is not shareable by default

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-service-broker#99]
- [x] Update the service broker config (in config/catalog.yml) to specify `"shareable": false` as described in the [Pivotal documentation](https://docs.pivotal.io/pivotalcf/2-4/services/enable-sharing.html).

- [x] Note in the README that service instance sharing is disabled by default and to use the service broker, one service instance should be provisioned per space

- [ ] Add a code comment to indicate the org / space GUIDs used in Conjur are those of the service instances (not the apps)

**Comment by izgeri** [comment]
from the pivotal docs:
 > The `context.space_guid` field represents the space where the service instance was created, and `bind_resource.space_guid` represents the space of the app involved in the binding.

**Comment by jtuttle** [comment]
@izgeri The docs say leaving the flag blank has the same effect as setting it to false. Is there any reason to add the flag, then?

**Comment by izgeri** [comment]
@jtuttle just seeing your note, but commenting here for posterity that the reason to add it is to make sure it is explicit that we do not allow sharing of service instances, rather than relying on the default behavior.
